#!/usr/bin/env python3
"""Seed the D1 `tools` table from the YAML tool configs.

Workers have no filesystem access, so this seeding step runs OUTSIDE the Worker
(plain Python) and pipes generated SQL into `wrangler d1 execute`.

sort_order strategy (see 01-phase1-worker-api-d1.md):
    A single, globally increasing sequence walked category by category. Within
    each category, tools with an explicit `homepage_order` come first in that
    order; the remaining tools are appended in deterministic (alphabetical id)
    order. Category walk order is image -> document -> data (approved decision;
    the flat 404 "Popular Tools" list in Phase 2 is the only consumer of the
    cross-category order — the homepage/category pages regroup per category).

Usage:
    python seed.py --print            # dry run: print the SQL, touch nothing
    python seed.py --out seed.sql     # write the SQL to a file
    python seed.py --local            # apply to local D1 (wrangler --local)
    python seed.py --remote           # apply to remote D1 (wrangler --remote)
    python seed.py --local --only-new # insert missing tools only, never
                                      # overwrite existing rows (use this once
                                      # the Phase 4 admin panel manages order)
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml (it's in requirements.txt)")

# Walk categories in this order to build the global sequence. Any category not
# listed here (e.g. a future 'audio-video') is appended afterwards, sorted by
# name, so new categories never break the deterministic run.
CATEGORY_ORDER = ["image-conversion", "document-tools", "data-conversion"]

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIR = REPO_ROOT / "tools"
DB_NAME = "filecast-db"


def load_tools() -> list[dict]:
    tools = []
    for path in sorted(TOOLS_DIR.glob("*.yaml")):
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not data or "id" not in data:
            print(f"  ! skipping {path.name}: no id", file=sys.stderr)
            continue
        tools.append(data)
    return tools


def category_rank(category: str) -> int:
    """Known categories sort by their fixed index; unknowns sort last, grouped
    by name (offset keeps them after all known categories deterministically)."""
    if category in CATEGORY_ORDER:
        return CATEGORY_ORDER.index(category)
    return len(CATEGORY_ORDER)


def ordered_tools(tools: list[dict]) -> list[dict]:
    """Return tools in global sort_order sequence."""
    def sort_key(t: dict):
        cat = t.get("category", "")
        # homepage_order present -> that value; absent -> large sentinel so
        # explicitly-ordered tools lead, unordered ones follow by id.
        ho = t.get("homepage_order")
        has_ho = 0 if isinstance(ho, int) else 1
        ho_val = ho if isinstance(ho, int) else 0
        return (
            category_rank(cat),
            cat,          # keep unknown categories grouped by name
            has_ho,       # explicit homepage_order first
            ho_val,       # then by that order
            t["id"],      # then alphabetical id (deterministic tiebreak)
        )

    return sorted(tools, key=sort_key)


def sql_str(value) -> str:
    """SQLite string literal with single-quote escaping, or NULL."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def build_sql(tools: list[dict], only_new: bool) -> str:
    ordered = ordered_tools(tools)
    lines = [
        "-- Generated by seed.py — do not edit by hand.",
        f"-- {len(ordered)} tools, global sort_order 1..{len(ordered)} "
        f"(categories: {' -> '.join(CATEGORY_ORDER)}).",
    ]
    if only_new:
        conflict = "ON CONFLICT(id) DO NOTHING"
    else:
        # Refresh sort_order + enabled (initial YAML state) + updated_at on
        # re-run. Override columns (display_name, maintenance_message,
        # custom_max_file_size) are deliberately NOT touched so admin overlays
        # survive a re-seed.
        conflict = (
            "ON CONFLICT(id) DO UPDATE SET "
            "sort_order = excluded.sort_order, "
            "enabled = excluded.enabled, "
            "updated_at = excluded.updated_at"
        )

    for i, t in enumerate(ordered, start=1):
        enabled = 1 if t.get("enabled", True) else 0
        lines.append(
            "INSERT INTO tools (id, enabled, sort_order, updated_at) VALUES "
            f"({sql_str(t['id'])}, {enabled}, {i}, "
            "datetime('now')) " + conflict + ";"
        )
    return "\n".join(lines) + "\n"


def find_wrangler() -> list[str]:
    """Locate a runnable wrangler invocation, or exit with guidance.

    Returns the resolved executable path (not the bare name) so subprocess can
    launch it on Windows, where `wrangler`/`npx` are `.cmd` shims.
    """
    wrangler = shutil.which("wrangler")
    if wrangler:
        return [wrangler]
    npx = shutil.which("npx")
    if npx:
        return [npx, "wrangler"]
    sys.exit(
        "wrangler not found (node/npm not installed). Install Node.js, run "
        "`npm install` in worker/, then re-run. To preview SQL without "
        "wrangler use: python seed.py --print"
    )


def apply(sql: str, remote: bool) -> None:
    wrangler = find_wrangler()
    with tempfile.NamedTemporaryFile(
        "w", suffix=".sql", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(sql)
        tmp_path = tmp.name
    scope = "--remote" if remote else "--local"
    cmd = wrangler + ["d1", "execute", DB_NAME, scope, f"--file={tmp_path}"]
    print(f"  running: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, check=True, cwd=Path(__file__).resolve().parent)
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def main() -> None:
    ap = argparse.ArgumentParser(description="Seed D1 tools table from YAML.")
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--print", action="store_true", dest="print_only",
                       help="print SQL to stdout (dry run)")
    group.add_argument("--out", metavar="FILE", help="write SQL to a file")
    group.add_argument("--local", action="store_true",
                       help="apply to local D1 via wrangler --local")
    group.add_argument("--remote", action="store_true",
                       help="apply to remote D1 via wrangler --remote")
    ap.add_argument("--only-new", action="store_true",
                    help="insert missing tools only; never overwrite existing "
                         "rows (ON CONFLICT DO NOTHING)")
    args = ap.parse_args()

    tools = load_tools()
    if not tools:
        sys.exit("No tools found in " + str(TOOLS_DIR))
    sql = build_sql(tools, only_new=args.only_new)

    if args.print_only:
        sys.stdout.write(sql)
    elif args.out:
        Path(args.out).write_text(sql, encoding="utf-8")
        print(f"  wrote {args.out} ({len(tools)} tools)")
    else:
        apply(sql, remote=args.remote)
        print(f"  seeded {len(tools)} tools")


if __name__ == "__main__":
    main()
